book/urls.py
from django.conf.urls.static import static
from django.urls import path
from .views import *
from django.conf import settings
from django.contrib.auth import views as auth_views
from .forms import LoginForm, MyPasswordResetForm, MySetPasswordForm, MyPasswordChangeForm


urlpatterns = [
    path('',home,name='home'),
    path('about/',about,name='about'),
    path('contact/',contact,name='contact'),
    path('category/<slug:val>',CategoryView.as_view(),name='category'),
    path('category_title/<val>',CategoryTitle.as_view(),name='category_title'),
    path('book_detail/<int:pk>',BookDetail.as_view(),name='book_detail'),
    path('all-books/', AllBooksView.as_view(), name='all_books_view'),
    path('profile/',ProfileView.as_view(),name='profile'),
    path('address/', address, name='address'),
    path('updateaddress/<int:pk>',UpdateAddress.as_view(),name='updateaddress'),
    path('deleteaddress/<int:pk>',DeleteAddress.as_view(),name='deleteaddress'),
    path('paymentdone/',payment_done,name='paymentdone'),
    path('orders/',home,name='orders'),
    path('add_books/',add_book,name='add_books'),
    path('update_book/<int:pk>/', UpdateBook.as_view(), name='update_book'),
    path('delete_book/<int:pk>/', DeleteBook.as_view(), name='delete_book'),
    path('books/', BookListView.as_view(), name='books'),



    path('add_to_cart',add_to_cart,name='add_to_cart'),
    path('cart/',show_cart,name='showcart'),
    path('checkout/',checkout.as_view(),name='checkout'),


    path('pluscart/',plus_cart),
    path('minuscart/',minus_cart),
    path('removecart/',remove_cart),

                  #Login authentication
    path('registration/',CustomerRegistrationView.as_view(),name='customerragistration'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='login.html', authentication_form=LoginForm), name='login'),
    path('password_change/',auth_views.PasswordChangeView.as_view(template_name='change_password.html',form_class=MyPasswordChangeForm,success_url='/password_change_done'),name="password_change"),
    path('password_change_done/',auth_views.PasswordChangeDoneView.as_view(template_name='password_change_done.html'),name='password_change_done'),
    path('logout/',Logout,name='logout'),
    path('adminHome',adminHome,name='adminHome'),
    path('login1/', Login1, name='login1'),
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='password_reset.html',form_class=MyPasswordResetForm),name='password_reset'),
    path('password_reset/done',auth_views.PasswordChangeDoneView.as_view(template_name='password_reset_done.html'),name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html',form_class=MySetPasswordForm),name='password_reset_confirm'),
    path('password_reset_complete',auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),name='password_reset_complete'),


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bookstore/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('book.urls')),
]

book/models.py
from django.contrib.auth.models import User
from django.db import models

CATEGORY_CHPICES=(
    ('FB','Fiction Books'),
    ('NB','Non Fiction Books'),
    ('MB','Mystery Books'),
    ('EC','Education Books')
)

STATE_CHOICES = (
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Goa', 'Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jharkhand', 'Jharkhand'),
    ('Karnataka', 'Karnataka'),
    ('Kerala', 'Kerala'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ('West Bengal', 'West Bengal'),
    ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'),
    ('Chandigarh', 'Chandigarh'),
    ('Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli and Daman and Diu'),
    ('Delhi', 'Delhi'),
    ('Lakshadweep', 'Lakshadweep'),
    ('Puducherry', 'Puducherry'),
)

STATUS_CHOICES = (
    ('Accepted','Accepted'),
    ('Packed','Packed'),
    ('On the way','On the way'),
    ('Delivered','Delivered'),
    ('Cancel','Cancel'),
    ('Pending','Pending'),
)

class Book(models.Model):
    title=models.CharField(max_length=100)
    selling_price=models.FloatField()
    discount_price=models.FloatField()
    description=models.TextField()
    composition=models.TextField(default='')
    prodapp=models.TextField(default='')
    category = models.CharField(choices=CATEGORY_CHPICES,max_length=2)
    book_image=models.ImageField(upload_to='book')
    def __str__(self):
        return self.title


class Customer(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    locality = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    mobile = models.BigIntegerField(default=0)
    pincode = models.IntegerField()
    state = models.CharField(choices=STATE_CHOICES,max_length=100)
    def __str__(self):
        return self.name

class Cart(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    @property
    def total_cost(self):
        return self.quantity * self.book.discount_price

class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    amount = models.FloatField()
    razorpay_order_id = models.CharField(max_length=100,blank=True,null=True)
    razorpay_payment_status = models.CharField(max_length=100,blank=True,null=True)
    razorpay_payment_id = models.CharField(max_length=100,blank=True,null=True)
    paid=models.BooleanField(default=False)

class OrderPlaced(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE)
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    ordered_date =models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50,choices=STATUS_CHOICES,default='pending')
    payment = models.ForeignKey(Payment,on_delete=models.CASCADE,default='')
    @property
    def total_cost(self):
        return self.quantity * self.book.discount_price

templates/add_book.html
{% extends 'adminnavbar.html' %}
{% load static %}

{% block title %}ADD BOOK{% endblock title %}

{% block main-content %}
<br/><br/><br/>
    <h2>Add Book</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="id_title">Title:</label>
        {{ form.title }}
        <br>
        <label for="id_selling_price">Selling Price:</label>
        {{ form.selling_price }}
        <br>
        <label for="id_discount_price">Discount Price:</label>
        {{ form.discount_price }}
        <br>
        <label for="id_description">Description:</label>
        {{ form.description }}
        <br>
        <label for="id_composition">Composition:</label>
        {{ form.composition }}
        <br>
        <label for="id_prodapp">Prodapp:</label>
        {{ form.prodapp }}
        <br>
        <label for="id_category">Category:</label>
        {{ form.category }}
        <br>
        <label for="id_book_image">Book Image:</label>
        {{ form.book_image }}
        <br>
        <button type="submit">Add Book</button>
    </form>
<br/><br/><br/>
{% endblock main-content %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_book.css' %}">
{% endblock styles %}

templates/addtocart.html
{% extends 'projectnavbar.html' %}
{% load static %}

{% block title %}Shopping Cart{% endblock title %}

{% block main-content %}
<br/><br/><br/>
<div class="container my-5">
    <div class="row">
        {% if cart %}
        <div class="col-md-8">
            <h1 class="mb-5">Shopping Cart</h1>
            <div class="card">
                <div class="card-body">
                    <h3>Cart</h3>
                    {% for item in cart %}
                    <div class="row mb-3">
                        <div class="col-sm-3 text-center">
                            <img src="{{ item.book.book_image.url }}" alt="{{ item.book.title }}" class="img-fluid img-thumbnail" height="150" width="150">
                        </div>
                        <div class="col-sm-9">
                            <div>
                                <h5>{{ item.book.title }}</h5>
                                <p class="text-muted">{{ item.book.description }}</p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="quantity-control">
                                        <label for="quantity">Quantity:</label>
                                        <a class="minus-cart btn" pid="{{ item.book.id }}"><i class="fa-solid fa-minus-circle"></i></a>
                                        <span id="quantity">{{ item.quantity }}</span>
                                        <a class="plus-cart btn" pid="{{ item.book.id }}"><i class="fa-solid fa-plus-circle"></i></a>
                                        <a class="remove-cart btn btn-sm btn-danger" href="#" pid={{item.book.id}}>Remove item</a>
                                    </div>
                                    <div>
                                        <p class="mb-0"><strong>Rs. {{ item.book.discount_price }}</strong></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr class="text-muted">
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <h3>Total Amount</h3>
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Amount
                            <span class="badge bg-primary rounded-pill" id="amount">Rs. {{ amount }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            Shopping
                            <span class="badge bg-primary rounded-pill">Rs. 40.00</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center">
                            <strong>Total (including GST)</strong>
                            <span class="badge bg-success rounded-pill" id="totalamount">Rs. {{ totalamount }}</span>
                        </li>
                    </ul>
                    <div class="d-grid mt-3">
                        <a href="{% url 'checkout' %}" class="btn btn-primary">Place Order</a>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="col-md-12 text-center">
            <h1 class="mb-5">Cart is Empty</h1>
        </div>
        {% endif %}
    </div>
</div>
<br/><br/><br/>
{% endblock main-content %}

templates/adminhomepage.html
{% extends 'adminnavbar.html' %}
{% load static %}
{% block title %}Admin Home Page{% endblock title %}
{% block main-content %}
<br/><br/><br/>
<h1 align="center">Home Page of navbar</h1>
{% endblock main-content %}

templates/adminnavbar.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Online Book Store</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</head>
</html>


<nav class="navbar navbar-expand-lg navbar-dark fixed-top" style="background-color: #A93226">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#"><b>Home</b></a>
                </li>
                 <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_books' %}"><b>Add Books</b></a>
                </li>
                <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'books' %}"><b>View Books</b></a>
                </li>
            </ul>

            <ul class="navbar-nav ms-auto">
    {% if user.is_authenticated %}
    <li class="nav-item me-3">
        <span class="nav-link">Welcome, {{ user.username }}</span>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url 'logout' %}"><strong>Logout</strong></a>
    </li>
    {% else %}
    <li class="nav-item me-3">
        <a class="nav-link" href="" style="color: black;">Register</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="" style="color: black;">Login</a>
    </li>
    {% endif %}
</ul>
        </div>
    </div>
</nav>


{% block main-content %}{% endblock main-content %}
{% block styles %}{% endblock styles %}

<!-- Footer -->
<footer id="sticky-footer" class="flex-shrink-0 py-2">
    <div class="container text-center">
        <small>Copyright Shashank. All Rights Reserved</small>
    </div>
</footer>

<!-- Custom styling for the footer -->
<style>
    #sticky-footer {
        position: fixed;
        bottom: 0;
        left: 0;
        right: 0;
        background-color: #A93226;
        color: white;
        padding: 10px;
        font-weight: bold;
    }

    /* Custom dropdown styles */
    .dropdown {
        position: relative;
        display: inline-block;
    }
</style>

templates/all_books.html
{% extends 'projectnavbar.html' %}
{% load static %}
{% block title %}All Books{% endblock title %}

{% block main-content %}
<br/><br/><br/><br/>
<div>
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                {% for boook in books %}
                <div class="col text-center mb-4">
                    <a href="{% url 'book_detail' boook.id %}" class="btn">
                        <div>
                            <img src="{{boook.book_image.url}}" width="300px" height="400px"/>
                            <div class="fw-bold">{{boook.title}}</div>
                            <div class="fw-bold text-success">
                                Rs.{{boook.discount_price}}/-
                                <small class="fw-light text-decoration-line-through"><del>{{boook.selling_price}}</del></small>
                            </div>
                        </div>
                    </a>
                    <div class="buttons row flex" style="font-family: 'Roboto'; display: flex; justify-content: center; align-items: center;">
                <button class="d-flex gap2 btn1 btn btn-danger p-1 m-1 btn-lg text-decoration-none text-white" type="submit"><i class="fa-solid fa-cart-shopping"></i>
                    Add to cart
                </button>
                <div class="btn btn-dark p-1 m-1 btn-lg">
                    <a href="#" class="text-decoration-none text-white"><i class="fa-brands fa-buy-n-large"></i> Buy Now</a>
                </div>
            </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<br/><br/><br/>
{% endblock main-content %}

templates/all_books1.html
{% extends 'adminnavbar.html' %}
{% load static %}
{% block title %}All Books{% endblock title %}

{% block main-content %}
<br/><br/><br/><br/>
<div>
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                {% for boook in books %}
                <div class="col text-center mb-4">
                    <a href="{% url 'book_detail' boook.id %}" class="btn">
                        <div>
                            <img src="{{boook.book_image.url}}" width="300px" height="400px"/>
                            <div class="fw-bold">{{boook.title}}</div>
                            <div class="fw-bold text-success">
                                Rs.{{boook.discount_price}}/-
                                <small class="fw-light text-decoration-line-through"><del>{{boook.selling_price}}</del></small>
                            </div>
                        </div>
                    </a>
                    <button class="btn btn-warning p-1 m-1 btn-lg">
        <a href="{% url 'update_book' pk=boook.id %}" class="text-decoration-none text-white">
            <i class="fa-solid fa-edit"></i> Update
        </a>
    </button>
    <button class="btn btn-danger p-1 m-1 btn-lg">
        <a href="{% url 'delete_book' pk=boook.id %}" class="text-decoration-none text-white">
            <i class="fa-solid fa-trash"></i> Remove
        </a>
    </button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<br/><br/><br/>
{% endblock main-content %}

templates/bookdetail.html
{% extends 'projectnavbar.html' %}
{% load static %}
{% block title %}Category{% endblock title %}

{% block main-content %}
<br/><br/><br/><br/>
<div class="container">
    <div class="row flex justify-content-between">
        <div>
            <img src="{{book.book_image.url}}" class="col-xs-6 col-sm-12 col-lg-12 mt-3 text-sm-center alt="Book Image" width="200" height="400">
        </div>
        <div class="productdetail col-lg-5">
            <h1 style="font-family: Lucida Console; font-size: 25px;">{{book.title}}</h1>
            <h5>Rs.{{book.discount_price}}/-</h5>
            <small class="tect-decoration-line-through text-muted fs-5"><del>Rs.{{book.selling_price}}</del></small>
            <br/><br/>
            <h4>Book Features</h4>
            <ul class="fs-5" style="font-family: Rajdhani;">
                <li>{{book.description}}</li>
            </ul>
                <form action="/add_to_cart" class="d-inline">
                    <input type="hidden" name="book_id" value="{{book.id}}">
                        <button class="btn btn-primary shadow px-5 py-2" type="submit"><i class="fa-solid fa-cart-shopping"></i>
                            Add to cart
                        </button>
                </form>
                    <a href="{% url 'showcart' %}" class="btn btn-warning shadow px-5 py-2 ms-4text-decoration-none text-white"><i class="fa-brands fa-buy-n-large"></i> Buy Now</a>
        </div>
    </div>
</div>
<br/><br/><br/>
{% endblock main-content %}

templates/category.html
{% extends 'projectnavbar.html' %}
{% load static %}
{% block title %}Category{% endblock title %}

{% block main-content %}
<br/><br/><br/>
<div>
    <div class="row">
        <div class="col-sm-12">
            <div class="row">
                {% for boook in book %}
                <div class="col text-center mb-4">
                    <a href="{% url 'book_detail' boook.id %}" class="btn">
                        <div>
                            <img src="{{boook.book_image.url}}" width="300px" height="400px"/>
                            <div class="fw-bold">{{boook.title}}</div>
                            <div class="fw-bold text-success">
                                Rs.{{boook.discount_price}}/-
                                <small class="fw-light text-decoration-line-through"><del>{{boook.selling_price}}</del></small>
                            </div>
                        </div>
                    </a>
                    <div class="buttons row flex" style="font-family: 'Roboto'; display: flex; justify-content: center; align-items: center;">
                <button class="d-flex gap2 btn1 btn btn-danger p-1 m-1 btn-lg text-decoration-none text-white" type="submit"><i class="fa-solid fa-cart-shopping"></i>
                    Add to cart
                </button>
                <div class="btn btn-dark p-1 m-1 btn-lg">
                    <a href="#" class="text-decoration-none text-white"><i class="fa-brands fa-buy-n-large"></i> Buy Now</a>
                </div>
            </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<br/><br/>
{% endblock main-content %}

templates/change_password.html
{% extends 'projectnavbar.html' %}
{% load static %}
{% block title %}Password Change Done{% endblock title %}

{% block main-content %}
<br/><br/><br/>
<div class="container my-5">
    <div class="row">
        <h3>Welcome <span class="text-capitalize">{{request.user}}</span></h3>
    </div>
    <div class="row">
        <div class="col-sm-2 border-end">
            <ul class="list-unstyled">
                <li class="d-grid"><a href="#" class="btn btn-primary">Change Password</a></li>
            </ul>
        </div>
        <div class="col-sm-8 offset-sm-1">
            <form action="" method="post" novalidate class="shadow p-5">
                {% csrf_token %}
                {% for fm in form %}
                    {{ fm.label_tag }} {{ fm }}<small class="text-danger">{{ fm.errors|striptags }}</small><br>
                {% endfor %}
                <div class="col-12 mt-3">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock main-content %}

templates/checkout.html
{% extends 'projectnavbar.html' %}
{% load static %}

{% block title %}Check Out{% endblock title %}

{% block main-content %}
<br/><br/><br/>

<div class="container">
    {% if messages %}
        {% for msg in messages %}
            <div class="alert alert-{{msg.tags}}" role="alert">
                {{msg}}
            </div>
        {% endfor %}
    {% endif %}
    <div class="row mt-5">
        <div class="col-sm-6">
            <h4>Order Summary</h4>
            <hr>
            {% for item in cart_items %}
            <div class="card-mb-2">
                <div class="card-body">
                    <h5>Book : {{item.book.title}}</h5>
                    <p>Quantity : {{item.quantity}}</p>
                    <p>Price : {{item.book.discount_price}}</p>
                </div>
            </div>
            {% endfor %}
            <p class="fw-bold">Total Cost + Rs.40 = {{totalamount}}</p>
            <small>Term and Conditions : Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer libero quam, dapibus ut interdum viverra, lacinia consectetur sem. Vestibulum placerat maximus magna, et ultrices erat pretium sit amet. Cras eleifend pretium risus. In hac habitasse platea dictumst. Duis varius laoreet quam non blandit. Mauris diam dui, eleifend ac elit eu, efficitur ornare purus. Curabitur nec sapien eget velit gravida ultrices quis ?</small>
        </div>
        <div class="col-sm-4 offset-sm-1">
            <h4>Select Shipping Address</h4>
            <hr>
            <form method="post" id="myform">
                {% csrf_token %}
                {% for ad in add %}
                <div class="card">
                    <div class="card-body">
                        <h5>{{ad.name}}</h5>
                        <p>Mobile : {{ad.mobile}}</p>
                        <p>{{ad.locality}} {{ad.city}} {{ad.state}} - {{ad.pincode}}</p>
                    </div>
                </div>
                <div class="form-check mt-2 mb-5">
                    <input class="form-check-input" type="radio" name="custid" id="custadd{{forloop.counter}}" value="{{ad.id}}">
                    <label class="form-check-label fw-bold" for="custadd{{forloop.counter}}">Address : {{forloop.counter}}</label>
                </div>
                {% endfor %}
                <div class="form-check mb-3">
                    <label for="totamount" class="form-label">Total Amount</label>
                    <input type="number" class="form-control" name="totamount" value={{totalamount}} readonly>
                </div>
                <div class="text-end">
                    <!--<button type="submit" class="btn btn-warning mt-3 px-5 fw-bold">Continue</button>-->
                    <button id="rzp-button1" type="submit" class="btn btn-warning mt-3 px-5 fw-bold">Payment</button>
                </div>
            </form>
        </div>
    </div>
</div>

<br/><br/><br/>
{% endblock main-content %}


{% block payment-gateway %}

<script>
var options = {
    "key": "rzp_test_B70fxkCYG7mhbZ",
    "amount": "{{razoramount}}",
    "currency": "INR",
    "name": "Giridhar Online Bookstore",
    "description": "Purchase Book",
    "order_id": "{{order_id}}",
    "handler": function (response) {
        console.log("Payment Success")
        var form = document.getElementById("myform");
        window.location.href = `http://127.0.0.1:8000/paymentdone?order_id=${response.id}&payment_id=${response.razorpay_payment_id}&cust_id=${form.elements["cust_id"].value}`;
    },
    "theme": {
        "color": "#3399cc"
    },
};

var rzp1 = new Razorpay(options);

rzp1.on('payment.failed', function (response) {
    alert(response.error.description);
});

document.getElementById('rzp-button1').onclick = function (e) {
    rzp1.open();
    e.preventDefault();
};
</script>




{% endblock payment-gateway %}

templates/login.html
{% extends 'projectnavbar.html' %}
{% load static %}
{% block title %}Login {% endblock title %}

{% block main-content %}
<br/><br/><br/>
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Login</h3>
            <hr>
            <form method="post" action="{% url 'login1' %}" novalidate class="shadow p-5">
                {% csrf_token %}
                {{ form.username.label_tag }} {{ form.username }}<small class="text-danger">{{ form.username.errors|striptags }}</small>
                <br>
                {{ form.password.label_tag }} {{ form.password }}<small class="text-danger">{{ form.password.errors|striptags }}</small>
                <br>
                <small><a href="{% url 'password_reset' %}">Forgot Password</a></small>
                <br>
                <input type="submit" class="btn btn-primary mt-4" value="Login">
                <div class="text-center text-primary fw-bold">
                    <small>New User? <a href="{% url 'customerragistration' %}" class="text-danger">Create an Account</a></small>
                </div>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock main-content %}

templates/password_reset.html
{% extends 'projectnavbar.html' %}
{% load static %}
{% block title %}Password Reset{% endblock title %}

{% block main-content %}
<br/><br/><br/>

<div class="container">
    <div class="my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Reset Password</h3>
            <hr>
            <form action="" method="post" novalidate class="shadow p-5">
                {% csrf_token %}
                {% for fm in form %}
                    {{ fm.label_tag }} {{ fm }}<small class="text-danger">{{ fm.errors|striptags }}</small><br>
                {% endfor %}
                <input type="submit" class="btn btn-primary mt-4" value="Submit">
                <br>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>

{% endblock main-content %}

templates/update_book.html
{% extends 'adminnavbar.html' %}
{% load static %}
{% block main-content %}
  <h2>Edit Book</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Book</button>
  </form>
{% endblock main-content %}

{% block styles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/add_book.css' %}">
{% endblock styles %}